# Site settings
title: Web Scratch
email: info@efcl.info
description: "ブラウザ/JavaScript等についてのブログ"
keywords:
  - "JavaScript"
  - "ブラウザ"
  - "ECMAScript"
  - "Objective-C"
  - "Firefox"
  - "拡張機能"
url: "http://efcl.info"
baseurl: ""
production_url : "http://efcl.info"
github_repo_url : https://github.com/efcl/efcl.github.io
timezone: Asia/Tokyo
encoding: utf-8
exclude:
  - README.md
  - config.rb
  - about/node_modules
  - vendor
  - circle.yml
# Setup
author:
  name: 'azu'
  url:  http://efcl.info/
  twitter: azu_re
  github:  azu

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/
# Github equal
safe: true
lsi: false
# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]
gems:
  - jekyll-sitemap
  - jemoji
# Prose
prose:
  rooturl: '_posts/'
  siteurl: 'http://efcl.info'
  media: 'wp-content/uploads'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "hidden"
          label: "Author"
          value: "azu"
          placeholder: "Trunk Botterson"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Post Tag"
          placeholder: "Create or choose"
          alterable: true
